// Generated by CoffeeScript 1.8.0
(function() {
  var destinationPattern, operation, options, program, put, sourcePattern, _ref;

  program = require('commander');

  put = require('./');

  program.version('0.1.0').usage('<source> <destination> [options]').option('-l, --link').option('-m, --move').option('-e, --extension <extensions>').option('-t, --type <types>').option('-v, --verbose').option('-s, --strict').option('-f, --force').parse(process.argv);

  if (program.extension || program.type || program.force) {
    throw new Error("--extension, --type and --force are not yet implemented");
  }

  if (program.link && program.move) {
    console.log("Cannot move and symlink a file at the same time. Pick either --move or --link, not both.");
  } else if (program.link) {
    operation = 'link';
  } else if (program.move) {
    operation = 'move';
  } else {
    operation = 'copy';
  }

  _ref = program.args, sourcePattern = _ref[0], destinationPattern = _ref[1];

  options = {
    verbose: program.verbose
  };

  put[operation](sourcePattern, destinationPattern, options);

}).call(this);
